server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portal_db
    password: chids123
    username: chids_p
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
