server:
  port: 8081

spring:
  datasource:
    username: chids_p
    password: Harrier#0252
    url: jdbc:mysql://localhost:3306/portal_db?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
